#!/usr/bin/env bash

case "$1" in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running."
    else
      /path/to/manage_my_process &
      echo $! > /var/run/my_process.pid
      echo "manage_my_process started."
    fi
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      kill -TERM "$pid"
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
    else
      echo "manage_my_process is not running."
    fi
    ;;
  restart)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      kill -TERM "$pid"
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
    fi
    /path/to/manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
